  import type { Metadata } from "next";
  import { Geist, Geist_Mono } from "next/font/google";
  import "./globals.css";
  import Header from "./components/Header";
  import Footer from "./components/Footer";
  import Link from "next/link";

  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  export const metadata: Metadata = {
    title: "Dự Án  Tốt Nghiệp",
    description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="vi" className={`${geistSans.variable} ${geistMono.variable}`}>
        <body>

          <Header />
          <section className="py-12 bg-gray-50">
            <div className="container mx-auto px-4">
              <h2 className="text-3xl md:text-4xl font-bold mb-8 text-center text-teal-700">
              </h2>
            </div>
          </section>
          {children}
          <Footer />
        </body>
      </html>
    );
  }

