import type { Metadata } from "next";
  import { Geist, Geist_Mono } from "next/font/google";
  import "./globals.css";
  import Header from "./components/Header";
  import Footer from "./components/Footer";
  import HeroSlider from "./components/HeroSlider";
  import AboutCompany from "./components/AboutCompany";
  import Strengths from "./components/Strengths";
  import Partners from "./components/Partners";
  import Link from "next/link";

  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  export const metadata: Metadata = {
    title: "Phụ Tùng Xe Máy",
    description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="vi" className={`${geistSans.variable} ${geistMono.variable}`}>
        <body>

          <Header />
           <HeroSlider />
           <AboutCompany />
           <Strengths />
          {children}
           <Partners />
          <Footer />
        </body>
      </html>
    );
  }

